name: htr_env 

channels:
  - pytorch           
  - nvidia          
  - conda-forge
  - defaults

dependencies:
  - python=3.11         
  - torch==2.6.0+cu124
  - torchvision==0.21.0+cu124
  - torchaudio==2.6.0+cu124
  - cudatoolkit=12.1.1 # Explicitly specify if needed, but pytorch channel often brings it
  - pip=24.0
  - numpy
  - pandas
  - scikit-learn
  # ... other conda-installable packages ...
  - pip:
    - transformers==4.52.4
    - datasets==3.6.0
    - jiwer==4.0.0
    - evaluate==0.4.4
    - timm==1.0.15
    - einops==0.8.1
    - mlflow==3.1.0
